In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
Cov_Mod_df = pd.read_csv("/BioII/lulab_b/huangkeyun/zhangys/alkb-seq/resources/Cov_Mod.txt",sep = '\t')
Cov_Mod_df['last_part'] = Cov_Mod_df['sample'].str.split('|').str[-1]
Cov_Mod_df['label'] = Cov_Mod_df['last_part'].map({'same': 0, 'diff': 1})
Cov_Mod_df

,sample,cov_1,cov_2,cov_3,cov_4,cov_5,cov_6,cov_7,cov_8,cov_9,...,RNA-editing.V33,RNA-editing.V34,RNA-editing.V35,RNA-editing.V36,RNA-editing.V37,RNA-editing.V38,RNA-editing.V39,RNA-editing.V40,last_part,label
0,NR_145819_____1|10776|same,1.000000,0.968750,0.953125,0.984375,0.984375,0.984375,0.718750,0.703125,0.671875,...,0,0,0,0,0,0,0,0,same,0
1,NR_146144_____1|10748|same,1.000000,0.975610,0.951220,0.804878,0.780488,0.780488,0.731707,0.682927,0.463415,...,0,0,0,0,0,0,0,0,same,0
2,NR_146152_____1|103|same,0.758621,0.758621,0.724138,0.310345,0.310345,0.275862,0.275862,0.275862,0.275862,...,0,0,0,0,0,0,0,0,same,0
3,NR_146154_____1|1910|same,0.117647,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,...,0,0,0,0,0,0,0,0,same,0
4,NR_145819_____1|7151|diff,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,diff,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,ENST00000622628_____1|400|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,same,0
764,ENST00000636175_____1|1662|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,same,0
765,NR_146117_____1|811|same,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,...,0,0,0,0,0,0,0,0,same,0
766,31895|25|same,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,...,0,0,0,0,0,0,0,0,same,0
767,ENST00000583516_____1|1312|diff,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,...,0,0,0,0,0,0,0,0,diff,1

In [3]:
samples_df = Cov_Mod_df.iloc[:, 0:-1-1]
samples_df

,sample,cov_1,cov_2,cov_3,cov_4,cov_5,cov_6,cov_7,cov_8,cov_9,...,RNA-editing.V31,RNA-editing.V32,RNA-editing.V33,RNA-editing.V34,RNA-editing.V35,RNA-editing.V36,RNA-editing.V37,RNA-editing.V38,RNA-editing.V39,RNA-editing.V40
0,NR_145819_____1|10776|same,1.000000,0.968750,0.953125,0.984375,0.984375,0.984375,0.718750,0.703125,0.671875,...,0,0,0,0,0,0,0,0,0,0
1,NR_146144_____1|10748|same,1.000000,0.975610,0.951220,0.804878,0.780488,0.780488,0.731707,0.682927,0.463415,...,0,0,0,0,0,0,0,0,0,0
2,NR_146152_____1|103|same,0.758621,0.758621,0.724138,0.310345,0.310345,0.275862,0.275862,0.275862,0.275862,...,0,0,0,0,0,0,0,0,0,0
3,NR_146154_____1|1910|same,0.117647,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,...,0,0,0,0,0,0,0,0,0,0
4,NR_145819_____1|7151|diff,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,ENST00000622628_____1|400|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
764,ENST00000636175_____1|1662|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
765,NR_146117_____1|811|same,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,...,0,0,0,0,0,0,0,0,0,0
766,31895|25|same,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,...,0,0,0,0,0,0,0,0,0,0
767,ENST00000583516_____1|1312|diff,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,...,0,0,0,0,0,0,0,0,0,0

In [5]:
sequence_df = pd.read_csv("/BioII/lulab_b/huangkeyun/zhangys/alkb-seq/resources/seq_struc.csv", names = ['sample', 'score1', 'score2', 'struc', 'sequence'])
sequence_df
#Cov_Mod_df['sequence']

,sample,score1,score2,struc,sequence
0,>NR_145819_____1|10776|same,0.158655,-6.3,..............(((..((((....)))).))).....,ACAATGTAGGTAAGGGAAGTCGGCAAGCCGGATCCGTAAC
1,>NR_146144_____1|10748|same,0.841345,-7.5,.(((...(((..((((....)))).)))...)))......,AGGTAAGGGAAGTCGGCAAGCCGGATCCGTAACTTCGGGA
2,>NR_146152_____1|103|same,0.158655,-3.1,(((((..((((...))))....))))).............,AACTGCGAATGGCTCATTAAATCAGTTATGGTTCCTTTGG
3,>NR_146154_____1|1910|same,0.841345,-9.8,..(((((..((((..((....)).)))).....)))))..,CCGGGTTAAGGCGCCCGATGCCGACGCTCATCAGACCCCA
4,>NR_145819_____1|7151|diff,0.158655,-16.0,((((...(((((((........)))).))).)))).....,CGGCCCCGGCCGGGTGGAAGGTCCCGTGCCCGTCGTCGTC
...,...,...,...,...,...
763,>ENST00000622628_____1|400|same,0.158655,-9.5,........((((((((((((....)).))).))..))))),CACCAGCACTTCCTCCCACGTGCGCGCTGGAGAACGGAAG
764,>ENST00000636175_____1|1662|same,0.158655,-12.5,..((((.((.((((((........)).)))).)).)))).,CTGGGGGCGGGTTCTCAAAGCGAAGAAGGACGTGGCTCTT
765,>NR_146117_____1|811|same,0.841345,-15.2,.......((((((...((((((....)).)))).)))))),AGCGTCGGCTCCGCCTGGGCCCTTGCGGTGCTCCTGGAGC
766,>31895|25|same,0.158655,-14.6,..........(((((((((((.....)).)))))))))..,TGTGGCGCAATCGGTTAGCGCGTTCGGCTGTTAACCGAAA
767,>ENST00000583516_____1|1312|diff,0.841345,-0.7,................(((........)))..........,ACCCATCTGACCTCTCCCTTCCTCCCCAGGCTGCTCCTTG

In [6]:
# 检查 'Sequence' 列是否包含 'N'，并删除包含 'N' 的行
original_row_count = len(sequence_df)  # 原始行数
localization_df = sequence_df[~sequence_df['sequence'].str.contains('N')]  # 保留不包含 'N' 的行
new_row_count = len(sequence_df)  # 处理后行数

# 计算删除的行数
deleted_rows = original_row_count - new_row_count

# 打印删除的行数
print(f"删除了 {deleted_rows} 行")

删除了 0 行

In [9]:
# 创建一个字典，将DNA碱基映射到one-hot编码
base_to_onehot = {
    'A': [1, 0, 0, 0],  # A -> [1, 0, 0, 0]
    'T': [0, 1, 0, 0],  # T -> [0, 1, 0, 0]
    'C': [0, 0, 1, 0],  # C -> [0, 0, 1, 0]
    'G': [0, 0, 0, 1]   # G -> [0, 0, 0, 1]
}

# 函数：将DNA序列转化为one-hot编码的展平向量
def sequence_to_onehot(sequence):
    onehot = []
    for base in sequence:
        onehot.extend(base_to_onehot.get(base, [0, 0, 0, 0]))  # 获取one-hot编码
    return onehot

# 将每个DNA序列转换为one-hot编码并展平
sequence_df['onehot_sequence'] = sequence_df['sequence'].apply(sequence_to_onehot)

In [12]:
sequence_df = pd.concat([samples_df, sequence_df['onehot_sequence']], axis=1)
sequence_df['onehot_sequence'] = sequence_df['onehot_sequence'].apply(lambda x: ''.join(map(str, x)))
sequence_df

,sample,cov_1,cov_2,cov_3,cov_4,cov_5,cov_6,cov_7,cov_8,cov_9,...,RNA-editing.V32,RNA-editing.V33,RNA-editing.V34,RNA-editing.V35,RNA-editing.V36,RNA-editing.V37,RNA-editing.V38,RNA-editing.V39,RNA-editing.V40,onehot_sequence
0,NR_145819_____1|10776|same,1.000000,0.968750,0.953125,0.984375,0.984375,0.984375,0.718750,0.703125,0.671875,...,0,0,0,0,0,0,0,0,0,1000001010001000010000010100100000010001010010...
1,NR_146144_____1|10748|same,1.000000,0.975610,0.951220,0.804878,0.780488,0.780488,0.731707,0.682927,0.463415,...,0,0,0,0,0,0,0,0,0,1000000100010100100010000001000100011000100000...
2,NR_146152_____1|103|same,0.758621,0.758621,0.724138,0.310345,0.310345,0.275862,0.275862,0.275862,0.275862,...,0,0,0,0,0,0,0,0,0,1000100000100100000100100001100010000100000100...
3,NR_146154_____1|1910|same,0.117647,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,0.058824,...,0,0,0,0,0,0,0,0,0,0010001000010001000101000100100010000001000100...
4,NR_145819_____1|7151|diff,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0010000100010010001000100010000100010010001000...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,ENST00000622628_____1|400|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0010100000100010100000010010100000100100010000...
764,ENST00000636175_____1|1662|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0010010000010001000100010001001000010001000101...
765,NR_146117_____1|811|same,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,...,0,0,0,0,0,0,0,0,0,1000000100100001010000100001000100100100001000...
766,31895|25|same,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,...,0,0,0,0,0,0,0,0,0,0100000101000001000100100001001010001000010000...
767,ENST00000583516_____1|1312|diff,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,...,0,0,0,0,0,0,0,0,0,1000001000100010100001000010010000011000001000...

In [17]:
new_df = sequence_df.copy()

# 函数：对每个onehot_sequence字符串进行重新排序
def reorder_onehot_sequence(sequence):
    # 将字符串转化为列表，按4个数字一组进行切割
    chunks = [sequence[i:i+4] for i in range(0, len(sequence), 4)]
    
    # 创建新的四个部分，分别对应每组的第一、第二、第三、第四个数字
    part1 = ''.join([chunk[0] for chunk in chunks])  # 每组的第一个数字
    part2 = ''.join([chunk[1] for chunk in chunks])  # 每组的第二个数字
    part3 = ''.join([chunk[2] for chunk in chunks])  # 每组的第三个数字
    part4 = ''.join([chunk[3] for chunk in chunks])  # 每组的第四个数字
    
    # 合并四部分并返回新的字符串
    return part1 + part2 + part3 + part4

# 对每一行的 'onehot_sequence' 列进行重新排序
new_df['onehot_sequence'] = new_df['onehot_sequence'].apply(reorder_onehot_sequence)
new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
new_df = new_df.drop(columns=['onehot_sequence'])

/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))
/tmp/ipykernel_139637/3875746896.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[['seq' + str(i+1) for i in range(160)]] = new_df['onehot_sequence'].apply(lambda x: pd.Series(list(x)))

In [21]:
new_df.to_csv('/BioII/lulab_b/huangkeyun/zhangys/alkb-seq/resources/sample_prepared.csv', sep = ',', index = None)